import type { ChatNode } from '../types/chatbot';

// Dialog tree data.comprehensive branching conversation
export const dialogTree: Record<string, ChatNode> = {
  root: {
    id: 'root',
    type: 'branch',
    text: "Hey there! I can point you to the right docs and answer common questions. What do you need help with?",
    textAr: "مرحباً! يمكنني توجيهك إلى المستندات المناسبة والإجابة على الأسئلة الشائعة. كيف يمكنني مساعدتك؟",
    category: 'root',
    options: [
      { label: "🔧 Something isn't working", labelAr: "🔧 هناك شيء لا يعمل", nextNodeId: 'troubleshoot-start' },
      { label: "🖥️ How do I set up a session?", labelAr: "🖥️ كيف أُعدّ جلسة؟", nextNodeId: 'session-start' },
      { label: "📊 Help me read a report", labelAr: "📊 ساعدني في فهم التقرير", nextNodeId: 'report-start' },
      { label: "👋 I'm new here (onboarding)", labelAr: "👋 أنا جديد هنا (تهيئة)", nextNodeId: 'onboarding-start' },
      { label: "🎯 Scoring & performance questions", labelAr: "🎯 أسئلة عن الدرجات والأداء", nextNodeId: 'scoring-start' },
      { label: "⚙️ Hardware & equipment", labelAr: "⚙️ الأجهزة والمعدات", nextNodeId: 'hardware-start' },
    ],
  },

  // ── TROUBLESHOOTING BRANCH ──
  'troubleshoot-start': {
    id: 'troubleshoot-start',
    type: 'branch',
    text: "Alright, let's sort this out. What's going wrong?",
    textAr: "حسناً، دعنا نحلّ المشكلة. ما الخلل الذي تواجهه؟",
    category: 'troubleshooting',
    options: [
      { label: "VR headset won't connect", labelAr: "نظارة VR لا تتصل", nextNodeId: 'ts-vr-connect' },
      { label: "Application won't launch", labelAr: "التطبيق لا يعمل", nextNodeId: 'ts-app-launch' },
      { label: "Operators can't join the session", labelAr: "المشغّلون لا يستطيعون الانضمام إلى الجلسة", nextNodeId: 'ts-join-session' },
      { label: "EmotiBit sensor issues", labelAr: "مشكلات في مستشعر EmotiBit", nextNodeId: 'ts-emotibit' },
      { label: "Missing camera feeds", labelAr: "بثّ الكاميرات مفقود", nextNodeId: 'ts-camera-feeds' },
      { label: "Report won't generate", labelAr: "التقرير لا يُولَّد", nextNodeId: 'ts-report-gen' },
    ],
  },
  'ts-vr-connect': {
    id: 'ts-vr-connect',
    type: 'answer',
    text: "VR Headset Connection Issues:\n\n1. Make sure the HTC Vive Focus Vision is fully charged (check the LED)\n2. Connect the headset to the PC using the Link Cable (USB)\n3. Open VIVE Hub / SteamVR on the PC\n4. Headset not detected? Try a different USB port\n5. Restart VIVE Hub and reconnect\n\nStill stuck? Escalate to IT support.",
    textAr: "مشكلات اتصال نظارة VR:\n\n1. تأكّد من أنّ HTC Vive Focus Vision مشحونة بالكامل (تحقّق من مؤشر LED)\n2. صِل النظارة بالحاسوب باستخدام Link Cable عبر USB\n3. افتح VIVE Hub / SteamVR على الحاسوب\n4. لم يتمّ اكتشاف النظارة؟ جرّب منفذ USB آخر\n5. أعِد تشغيل VIVE Hub وأعِد الاتصال\n\nهل لا تزال المشكلة قائمة؟ حوّل الأمر إلى دعم تقنية المعلومات.",
    category: 'troubleshooting',
    docLink: '/knowledge-base/mcc-troubleshooting-flowchart',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-app-launch': {
    id: 'ts-app-launch',
    type: 'answer',
    text: "Application Won't Launch:\n\n1. Close the application completely (check Task Manager for any running instances)\n2. Right-click the MCCVR application and select 'Run as Administrator'\n3. Ensure your GPU drivers are up to date (minimum RTX 2060 required)\n4. Check that Windows Firewall isn't blocking the application\n5. Verify the application files aren't corrupted (check file integrity)\n\nIf the issue persists, contact IT support with the error message.",
    textAr: "التطبيق لا يعمل:\n\n1. أغلق التطبيق بالكامل (تحقّق من Task Manager بحثاً عن أيّ نسخة قيد التشغيل)\n2. انقر بزرّ الفأرة الأيمن على تطبيق MCCVR واختر 'تشغيل كمسؤول'\n3. تأكّد من أنّ تعريفات GPU مُحدَّثة (الحدّ الأدنى RTX 2060)\n4. تحقّق من أنّ Windows Firewall لا يحظر التطبيق\n5. تأكّد من سلامة ملفات التطبيق (تحقّق من سلامة الملفات)\n\nإذا استمرّت المشكلة، تواصل مع دعم تقنية المعلومات مرفقاً رسالة الخطأ.",
    category: 'troubleshooting',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-join-session': {
    id: 'ts-join-session',
    type: 'answer',
    text: "Operators Can't Join Session:\n\n1. Confirm the Supervisor has created the scenario session first\n2. Verify all PCs are connected to the same network (check Ethernet cables)\n3. Check that the correct Server IP is configured (default: TCP port 7777)\n4. Ensure Windows Firewall allows MCCVR through (ports TCP 7777, UDP 7780+)\n5. Have operators close and relaunch the application\n6. If in VR, ensure the headset is properly connected via VIVE Hub\n\nThe Supervisor's waiting area should show connected operators.",
    textAr: "المشغّلون لا يستطيعون الانضمام إلى الجلسة:\n\n1. تأكّد من أنّ المشرف قد أنشأ جلسة السيناريو أولاً\n2. تحقّق من أنّ جميع أجهزة الحاسوب متصلة بالشبكة ذاتها (تحقّق من كابلات Ethernet)\n3. تأكّد من أنّ عنوان Server IP صحيح (الافتراضي: TCP منفذ 7777)\n4. تأكّد من أنّ Windows Firewall يسمح لـ MCCVR بالمرور (منافذ TCP 7777، UDP 7780+)\n5. اطلب من المشغّلين إغلاق التطبيق وإعادة تشغيله\n6. إذا كانوا في وضع VR، تأكّد من أنّ النظارة متصلة بشكل صحيح عبر VIVE Hub\n\nيجب أن تعرض منطقة الانتظار لدى المشرف المشغّلين المتصلين.",
    category: 'troubleshooting',
    docLink: '/knowledge-base/mcc-software-guide',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-emotibit': {
    id: 'ts-emotibit',
    type: 'answer',
    text: "EmotiBit Sensor Issues:\n\n1. Check the LED on the EmotiBit board:\n   • Green = Connected & streaming\n   • Blue = Powered on, searching for connection\n   • Red = Low battery or error\n2. Ensure the sensor is properly attached to the wrist strap\n3. Verify the EmotiBit is on the same local network as the PC\n4. Check that UDP port 12346 is open in the firewall\n5. Restart the EmotiBit by removing and reinserting the battery\n\nBiometric data is supplementary. Sessions can still run without it if needed.",
    textAr: "مشكلات مستشعر EmotiBit:\n\n1. تحقّق من مؤشر LED على لوحة EmotiBit:\n   • أخضر = متصل ويبثّ البيانات\n   • أزرق = قيد التشغيل، يبحث عن اتصال\n   • أحمر = بطارية منخفضة أو خطأ\n2. تأكّد من أنّ المستشعر مُثبَّت بشكل صحيح على سوار المعصم\n3. تحقّق من أنّ EmotiBit على الشبكة المحلية ذاتها مع الحاسوب\n4. تأكّد من أنّ منفذ UDP 12346 مفتوح في جدار الحماية\n5. أعِد تشغيل EmotiBit بإزالة البطارية وإعادة إدخالها\n\nالبيانات الحيوية تكميلية. يمكن تشغيل الجلسات بدونها عند الحاجة.",
    category: 'troubleshooting',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-camera-feeds': {
    id: 'ts-camera-feeds',
    type: 'answer',
    text: "Missing Camera Feeds:\n\n1. Ensure the scenario has been fully loaded (wait for the loading screen to complete)\n2. Check that the operator's monitor widget is set to the correct camera slot\n3. Try switching to a different camera and then switching back\n4. If the live wall is blank, verify the supervisor dashboard connection\n5. Check GPU performance, since feeds may drop if the system is under heavy load\n\nEach scenario has 4-6 cameras that should be visible.",
    textAr: "بثّ الكاميرات مفقود:\n\n1. تأكّد من أنّ السيناريو قد تمّ تحميله بالكامل (انتظر اكتمال شاشة التحميل)\n2. تحقّق من أنّ واجهة شاشة المشغّل مُعيَّنة على خانة الكاميرا الصحيحة\n3. جرّب التبديل إلى كاميرا أخرى ثمّ العودة\n4. إذا كان جدار البثّ فارغاً، تحقّق من اتصال لوحة تحكّم المشرف\n5. تحقّق من أداء GPU، إذ قد ينقطع البثّ إذا كان النظام تحت ضغط عالٍ\n\nيحتوي كلّ سيناريو على 4-6 كاميرات يجب أن تكون ظاهرة.",
    category: 'troubleshooting',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-report-gen': {
    id: 'ts-report-gen',
    type: 'answer',
    text: "Report Generation Issues:\n\n1. Wait for the scenario to fully complete.reports generate from saved session data\n2. Check the Data folder for the session files (Data/<SessionTimestamp>/)\n3. Ensure sufficient disk space is available\n4. Try regenerating the report from the supervisor dashboard\n5. If the PDF export fails, check that the training system plugin is properly loaded\n\nReports require all operator data to be flushed (happens automatically every 30 seconds during the session).",
    textAr: "مشكلات إنشاء التقارير:\n\n1. انتظر اكتمال السيناريو بالكامل. تُنشأ التقارير من بيانات الجلسة المحفوظة\n2. تحقّق من مجلد Data بحثاً عن ملفات الجلسة (Data/<SessionTimestamp>/)\n3. تأكّد من توفّر مساحة كافية على القرص\n4. جرّب إعادة إنشاء التقرير من لوحة تحكّم المشرف\n5. إذا فشل تصدير PDF، تأكّد من أنّ إضافة نظام التدريب مُحمَّلة بشكل صحيح\n\nتتطلّب التقارير حفظ جميع بيانات المشغّلين (يتمّ ذلك تلقائياً كلّ 30 ثانية أثناء الجلسة).",
    category: 'troubleshooting',
    docLink: '/knowledge-base/mcc-report-guide',
    options: [
      { label: "That fixed it, thanks!", labelAr: "تمّ حلّ المشكلة، شكراً!", nextNodeId: 'resolved' },
      { label: "Still not working", labelAr: "لا تزال المشكلة قائمة", nextNodeId: 'ts-escalate' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'ts-escalate': {
    id: 'ts-escalate',
    type: 'answer',
    text: "If things still aren't working after those steps:\n\n1. Document the exact error message or behavior\n2. Note which station/PC is affected\n3. Contact your IT Administrator first\n4. If IT cannot resolve, escalate to the Training Manager\n5. For software bugs, Vendor vendor support may be needed\n\nEscalation path: Operator → Supervisor → IT Staff → Training Manager → Vendor Support",
    textAr: "إذا لم تُحلّ المشكلة بعد اتباع هذه الخطوات:\n\n1. وثّق رسالة الخطأ أو السلوك بدقّة\n2. سجّل المحطة/الحاسوب المتأثّر\n3. تواصل مع مسؤول تقنية المعلومات أولاً\n4. إذا لم يتمكّن فريق تقنية المعلومات من الحلّ، حوّل الأمر إلى مدير التدريب\n5. لأخطاء البرمجيات، قد يكون دعم المورّد ضرورياً\n\nمسار التصعيد: مشغّل ← مشرف ← فريق تقنية المعلومات ← مدير التدريب ← دعم المورّد",
    category: 'troubleshooting',
    docLink: '/tools/troubleshooter',
    options: [
      { label: "Back to troubleshooting", labelAr: "العودة إلى استكشاف الأخطاء", nextNodeId: 'troubleshoot-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  resolved: {
    id: 'resolved',
    type: 'answer',
    text: "Good to hear! Need help with anything else?",
    textAr: "يسرّنا ذلك! هل تحتاج إلى مساعدة في أمر آخر؟",
    category: 'general',
    options: [
      { label: "Yes, I have another question", labelAr: "نعم، لديّ سؤال آخر", nextNodeId: 'root' },
      { label: "No, that's all. Thanks!", labelAr: "لا، هذا كلّ شيء. شكراً!", nextNodeId: 'goodbye' },
    ],
  },
  goodbye: {
    id: 'goodbye',
    type: 'answer',
    text: "Anytime! Hit the chat button whenever you need a hand. Best of luck with your session! 🎯",
    textAr: "في أيّ وقت! اضغط زرّ المحادثة متى ما احتجت إلى مساعدة. بالتوفيق في جلستك! 🎯",
    category: 'general',
    options: [
      { label: "Start over", labelAr: "البدء من جديد", nextNodeId: 'root' },
      { label: "🔍 Search the Knowledge Base", labelAr: "🔍 البحث في قاعدة المعرفة", nextNodeId: 'search-kb' },
    ],
  },
  'search-kb': {
    id: 'search-kb',
    type: 'answer',
    text: "You can search across all MCCVR documentation using the search bar at the top of the page (or press Ctrl+K). If you can't find what you need, check with your Supervisor or IT staff.",
    textAr: "يمكنك البحث في جميع وثائق MCCVR باستخدام شريط البحث في أعلى الصفحة (أو اضغط Ctrl+K). إذا لم تجد ما تحتاجه، راجع المشرف أو فريق تقنية المعلومات.",
    category: 'general',
    docLink: '/knowledge-base',
    options: [
      { label: "Start over", labelAr: "البدء من جديد", nextNodeId: 'root' },
    ],
  },

  // ── SESSION SETUP BRANCH ──
  'session-start': {
    id: 'session-start',
    type: 'branch',
    text: "What role are you in for this session?",
    textAr: "ما هو دورك في هذه الجلسة؟",
    category: 'session',
    options: [
      { label: "I'm an Operator (joining a session)", labelAr: "أنا مشغّل (أنضمّ إلى جلسة)", nextNodeId: 'session-operator' },
      { label: "I'm a Supervisor (hosting a session)", labelAr: "أنا مشرف (أستضيف جلسة)", nextNodeId: 'session-supervisor' },
      { label: "I'm a Facilitator (running training)", labelAr: "أنا ميسّر (أدير التدريب)", nextNodeId: 'session-facilitator' },
    ],
  },
  'session-operator': {
    id: 'session-operator',
    type: 'answer',
    text: "Operator Session Steps:\n\n1. Power on your workstation PC\n2. Turn on the EmotiBit sensor (make sure it's charged) and attach it to your wrist\n3. Open VIVE Hub on the PC (do not launch MCCVR yet)\n4. Connect the VR headset to the PC using the Link Cable (USB 3.0 port)\n5. Open the EmotiBit Oscilloscope app on the PC\n6. Select the correct EmotiBit device under output devices, and set transfer mode to UDP\n7. Launch the MCCVRVR client application (SteamVR opens automatically since VIVE Hub is running)\n8. Put on the VR headset\n9. In MCC, join the lobby and enter your name\n10. Wait for the Supervisor to start the session\n11. Complete the eye tracking calibration when prompted\n12. You'll see a 4-slot CCTV camera grid. Use the mouse or controller to switch cameras and PTZ",
    textAr: "خطوات جلسة المشغّل:\n\n1. شغّل حاسوب محطة العمل\n2. شغّل مستشعر EmotiBit (تأكّد من أنّه مشحون) وثبّته على معصمك\n3. افتح VIVE Hub على الحاسوب (لا تُشغّل MCCVR بعد)\n4. صِل نظارة VR بالحاسوب باستخدام Link Cable (منفذ USB 3.0)\n5. افتح تطبيق EmotiBit Oscilloscope على الحاسوب\n6. اختر جهاز EmotiBit الصحيح ضمن أجهزة الإخراج، واضبط وضع النقل على UDP\n7. شغّل تطبيق MCCVR للعميل (يُفتح SteamVR تلقائياً لأنّ VIVE Hub قيد التشغيل)\n8. ارتدِ نظارة VR\n9. في MCCVR، انضمّ إلى الردهة وأدخل اسمك\n10. انتظر حتى يبدأ المشرف الجلسة\n11. أكمل معايرة تتبّع العين عند ظهور المطالبة\n12. ستظهر لك شبكة كاميرات CCTV من 4 خانات. استخدم الفأرة أو وحدة التحكّم للتبديل بين الكاميرات واستخدام PTZ",
    category: 'session',
    docLink: '/knowledge-base/mcc-operator-quick-start',
    options: [
      { label: "What are the PTZ controls?", labelAr: "ما هي عناصر تحكّم PTZ؟", nextNodeId: 'session-ptz' },
      { label: "How do I mark suspects?", labelAr: "كيف أُعلّم المشتبه بهم؟", nextNodeId: 'session-marking' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-supervisor': {
    id: 'session-supervisor',
    type: 'answer',
    text: "Supervisor Session Steps:\n\n1. Power on the supervisor workstation\n2. Launch the MCCVRVR application in server mode\n3. Select a scenario (Airport, Embassy, Mall, Concert, or Protest)\n4. Create the lobby\n5. Wait for all operators to connect and join the lobby\n6. Start the session when everyone is ready\n7. Monitor operators via the Live Wall and individual feeds\n8. Use the dashboard to view biometrics and eye tracking data\n9. Trigger distractions or alarms as needed\n10. End session and generate reports",
    textAr: "خطوات جلسة المشرف:\n\n1. شغّل محطة عمل المشرف\n2. شغّل تطبيق MCCVR في وضع Server\n3. اختر سيناريو (مطار، سفارة، مركز تجاري، حفلة، أو احتجاج)\n4. أنشئ الردهة\n5. انتظر حتى يتصل جميع المشغّلين وينضمّوا إلى الردهة\n6. ابدأ الجلسة عندما يكون الجميع جاهزاً\n7. راقب المشغّلين عبر جدار البثّ المباشر والبثوث الفردية\n8. استخدم لوحة التحكّم لعرض البيانات الحيوية وبيانات تتبّع العين\n9. فعّل المشتّتات أو الإنذارات حسب الحاجة\n10. أنهِ الجلسة وأنشئ التقارير",
    category: 'session',
    docLink: '/knowledge-base/mcc-supervisor-quick-start',
    options: [
      { label: "How do I read the live monitoring dashboard?", labelAr: "كيف أقرأ لوحة المراقبة المباشرة؟", nextNodeId: 'session-live-monitor' },
      { label: "How do I generate reports?", labelAr: "كيف أُنشئ التقارير؟", nextNodeId: 'session-reports' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-facilitator': {
    id: 'session-facilitator',
    type: 'answer',
    text: "Facilitator Session Delivery (3.5 hours total):\n\n1. Pre-session: Verify all hardware, print materials, set up room\n2. Block 1.Get Oriented (30 min, 0:00–0:30): Welcome, system overview, hardware setup practice\n3. Block 2.Operators Learn by Doing (75 min, 0:30–1:45): Join session, first live scenario (Airport, 30 min), debrief (15 min), then a 15-minute break\n4. Block 3.Deeper Practice (60 min, 1:45–2:45): Second scenario (Embassy or Mall, 30 min), supervisor replay and reporting (15 min), operators self-review (15 min)\n5. Block 4.Prove It and Wrap Up (45 min, 2:45–3:30): Practical assessment (30 min), review and handover (15 min)\n\nRemember: 30% talking, 70% hands-on practice!",
    textAr: "تقديم جلسة الميسّر (3.5 ساعات إجمالاً):\n\n1. قبل الجلسة: تحقّق من جميع الأجهزة، اطبع المواد، جهّز الغرفة\n2. القسم 1. التعرّف على النظام (30 دقيقة، 0:00-0:30): ترحيب، نظرة عامة على النظام، تدريب على إعداد الأجهزة\n3. القسم 2. المشغّلون يتعلّمون بالممارسة (75 دقيقة، 0:30-1:45): الانضمام إلى الجلسة، أوّل سيناريو مباشر (المطار، 30 دقيقة)، مراجعة (15 دقيقة)، ثمّ استراحة 15 دقيقة\n4. القسم 3. تدريب أعمق (60 دقيقة، 1:45-2:45): سيناريو ثانٍ (السفارة أو المركز التجاري، 30 دقيقة)، إعادة تشغيل المشرف والتقارير (15 دقيقة)، مراجعة ذاتية للمشغّلين (15 دقيقة)\n5. القسم 4. إثبات الكفاءة والاختتام (45 دقيقة، 2:45-3:30): تقييم عملي (30 دقيقة)، مراجعة وتسليم (15 دقيقة)\n\nتذكّر: 30% شرح نظري، 70% تطبيق عملي!",
    category: 'session',
    docLink: '/knowledge-base/mcc-facilitator-guide-new',
    options: [
      { label: "Pre-session checklist", labelAr: "قائمة التحقّق قبل الجلسة", nextNodeId: 'session-pre-checklist' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-ptz': {
    id: 'session-ptz',
    type: 'answer',
    text: "PTZ (Pan/Tilt/Zoom) Controls:\n\nWhen viewing a camera feed in fullscreen, you'll see a joystick area on the monitor widget:\n\n• Pan: Drag left or right inside the joystick area\n• Tilt: Drag up or down inside the joystick area\n• Zoom In: Click the Zoom In button (narrows the field of view)\n• Zoom Out: Click the Zoom Out button (widens the field of view)\n• Reset: Click the Reset button to return to the default camera position\n\nOther controls:\n• Right-click on a person to mark them as suspicious\n• Left-click a camera feed to enter fullscreen\n• Double-click to exit fullscreen and return to the grid view\n\nIn VR, use the controller thumbstick for pan/tilt.",
    textAr: "عناصر تحكّم PTZ (تحريك/إمالة/تقريب):\n\nعند مشاهدة بثّ كاميرا في وضع ملء الشاشة، ستظهر لك منطقة عصا التحكّم على واجهة الشاشة:\n\n• التحريك: اسحب يميناً أو يساراً داخل منطقة عصا التحكّم\n• الإمالة: اسحب للأعلى أو للأسفل داخل منطقة عصا التحكّم\n• التقريب: انقر زرّ التقريب (يُضيّق مجال الرؤية)\n• التبعيد: انقر زرّ التبعيد (يُوسّع مجال الرؤية)\n• إعادة الضبط: انقر زرّ إعادة الضبط للعودة إلى وضع الكاميرا الافتراضي\n\nعناصر تحكّم أخرى:\n• انقر بزرّ الفأرة الأيمن على شخص لتعليمه كمشتبه به\n• انقر بزرّ الفأرة الأيسر على بثّ كاميرا للدخول في وضع ملء الشاشة\n• انقر نقراً مزدوجاً للخروج من وضع ملء الشاشة والعودة إلى عرض الشبكة\n\nفي وضع VR، استخدم عصا الإبهام على وحدة التحكّم للتحريك والإمالة.",
    category: 'session',
    options: [
      { label: "Back to operator setup", labelAr: "العودة إلى إعداد المشغّل", nextNodeId: 'session-operator' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-marking': {
    id: 'session-marking',
    type: 'answer',
    text: "Marking Suspects:\n\n1. When you spot suspicious behavior, point at the individual on the camera feed\n2. Right-click to mark them (a highlight will appear)\n3. Correct marks increase your Detection Accuracy score\n4. Incorrect marks (marking innocent people) count as False Positives and reduce your score\n5. Be deliberate. Quality over quantity\n\nTip: Look for unusual behavior patterns described in your scenario briefing.",
    textAr: "تعليم المشتبه بهم:\n\n1. عند ملاحظة سلوك مشبوه، أشِر إلى الشخص في بثّ الكاميرا\n2. انقر بزرّ الفأرة الأيمن لتعليمه (سيظهر تمييز)\n3. التعليمات الصحيحة تزيد درجة دقّة الكشف\n4. التعليمات الخاطئة (تعليم أشخاص أبرياء) تُحتسب كإيجابيات كاذبة وتُنقص درجتك\n5. كن دقيقاً ومتأنّياً. الجودة أهمّ من الكمّية\n\nنصيحة: ابحث عن أنماط السلوك غير المعتاد الموصوفة في ملخّص السيناريو.",
    category: 'session',
    options: [
      { label: "Back to operator setup", labelAr: "العودة إلى إعداد المشغّل", nextNodeId: 'session-operator' },
      { label: "Tell me about scoring", labelAr: "أخبرني عن نظام الدرجات", nextNodeId: 'scoring-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-live-monitor': {
    id: 'session-live-monitor',
    type: 'answer',
    text: "Live Monitoring Dashboard (Supervisor):\n\n• Live Wall: Grid showing all camera feeds across the scenario\n• Operator Feeds: Individual view of what each operator is watching\n• Biometric Panel: Real-time heart rate, skin conductance (stress indicator) for each operator\n• Eye Tracking: Gaze heatmap showing where operators are focusing attention\n• Alarm Panel: Status of triggered alarms and operator response times\n\nYou can click any operator to focus on their view and data.",
    textAr: "لوحة المراقبة المباشرة (المشرف):\n\n• جدار البثّ المباشر: شبكة تعرض جميع بثوث الكاميرات في السيناريو\n• بثوث المشغّلين: عرض فردي لما يشاهده كلّ مشغّل\n• لوحة البيانات الحيوية: معدّل نبض القلب والتوصيل الجلدي (مؤشّر التوتّر) لكلّ مشغّل بشكل آني\n• تتبّع العين: خريطة حرارية للنظر تعرض مواضع تركيز انتباه المشغّلين\n• لوحة الإنذارات: حالة الإنذارات المُفعَّلة وأوقات استجابة المشغّلين\n\nيمكنك النقر على أيّ مشغّل للتركيز على عرضه وبياناته.",
    category: 'session',
    options: [
      { label: "Back to supervisor setup", labelAr: "العودة إلى إعداد المشرف", nextNodeId: 'session-supervisor' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-reports': {
    id: 'session-reports',
    type: 'answer',
    text: "Generating Reports:\n\n1. End the scenario from the supervisor dashboard\n2. Wait for data to be flushed (automatic, takes ~30 seconds)\n3. Navigate to the Report section in the dashboard\n4. Select the operator(s) and session to review\n5. Reports are generated as PDFs with radar charts, action timelines, and scores\n\nAll session data is saved in the Data/<SessionTimestamp>/ folder.",
    textAr: "إنشاء التقارير:\n\n1. أنهِ السيناريو من لوحة تحكّم المشرف\n2. انتظر حفظ البيانات (تلقائي، يستغرق نحو 30 ثانية)\n3. انتقل إلى قسم التقارير في لوحة التحكّم\n4. اختر المشغّل (أو المشغّلين) والجلسة للمراجعة\n5. تُنشأ التقارير كملفات PDF تتضمّن مخطّطات رادارية وجداول زمنية للأحداث والدرجات\n\nتُحفظ جميع بيانات الجلسة في مجلد Data/<SessionTimestamp>/.",
    category: 'session',
    docLink: '/knowledge-base/mcc-report-guide',
    options: [
      { label: "How do I interpret the report?", labelAr: "كيف أُفسّر التقرير؟", nextNodeId: 'report-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'session-pre-checklist': {
    id: 'session-pre-checklist',
    type: 'answer',
    text: "Use the interactive Pre-Session Checklist in the Tools section to ensure everything is ready before your training session. It includes all hardware checks, software verification, and room preparation steps, and it saves your progress!",
    textAr: "استخدم قائمة التحقّق التفاعلية قبل الجلسة في قسم الأدوات للتأكّد من أنّ كلّ شيء جاهز قبل جلسة التدريب. تشمل جميع فحوصات الأجهزة والتحقّق من البرمجيات وخطوات تجهيز الغرفة، وتحفظ تقدّمك!",
    category: 'session',
    docLink: '/tools/checklists',
    options: [
      { label: "Back to facilitator guide", labelAr: "العودة إلى دليل الميسّر", nextNodeId: 'session-facilitator' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },

  // ── REPORT READING BRANCH ──
  'report-start': {
    id: 'report-start',
    type: 'branch',
    text: "What would you like to know about your performance reports?",
    textAr: "ماذا تودّ أن تعرف عن تقارير أدائك؟",
    category: 'report',
    options: [
      { label: "Understanding the Composite Score", labelAr: "فهم الدرجة الإجمالية", nextNodeId: 'report-composite' },
      { label: "What do the score labels mean?", labelAr: "ما معنى تصنيفات الدرجات؟", nextNodeId: 'report-labels' },
      { label: "Explain each scoring dimension", labelAr: "اشرح كلّ بُعد من أبعاد التقييم", nextNodeId: 'report-dimensions' },
      { label: "How to improve my score", labelAr: "كيف أُحسّن درجتي؟", nextNodeId: 'report-improve' },
    ],
  },
  'report-composite': {
    id: 'report-composite',
    type: 'answer',
    text: "Composite Score (0-100):\n\nYour overall score is a weighted average of 4 dimensions:\n\n• Detection Accuracy: 40%.How correctly you identified suspicious individuals\n• False Positives: 20%.Penalty for marking innocent people\n• Timeliness: 20%.How quickly you responded to events and alarms\n• Attention & Gaze: 20%.How well you distributed focus across all cameras\n\nThe composite score gives the overall picture of operator performance.",
    textAr: "الدرجة الإجمالية (0-100):\n\nدرجتك الإجمالية هي متوسّط مرجّح من 4 أبعاد:\n\n• دقّة الكشف: 40%. مدى صحّة تحديدك للأشخاص المشتبه بهم\n• الإيجابيات الكاذبة: 20%. عقوبة على تعليم أشخاص أبرياء\n• سرعة الاستجابة: 20%. مدى سرعة استجابتك للأحداث والإنذارات\n• الانتباه والنظر: 20%. مدى جودة توزيعك للتركيز على جميع الكاميرات\n\nتُعطي الدرجة الإجمالية الصورة الشاملة لأداء المشغّل.",
    category: 'report',
    docLink: '/tools/score-calculator',
    options: [
      { label: "What do the score labels mean?", labelAr: "ما معنى تصنيفات الدرجات؟", nextNodeId: 'report-labels' },
      { label: "Use the Score Calculator", labelAr: "استخدم حاسبة الدرجات", nextNodeId: 'report-calculator' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-labels': {
    id: 'report-labels',
    type: 'answer',
    text: "Score Rating Labels:\n\n• Excellent (90-100): Consistently strong across all dimensions. Ready for advanced scenarios.\n• Competent (70-89): Solid performance with minor areas for improvement. Meets the sign-off threshold.\n• Needs Improvement (50-69): Specific skills require focused practice sessions.\n• Low (30-49): Significant gaps in multiple areas. Additional training recommended.\n• Critical (Below 30): Fundamental skills need development. Requires mentored re-training.\n\nThe sign-off threshold for onboarding is 70% (Competent).",
    textAr: "تصنيفات الدرجات:\n\n• ممتاز (90-100): أداء قوي ومتّسق في جميع الأبعاد. جاهز لسيناريوهات متقدّمة.\n• كفؤ (70-89): أداء جيّد مع مجالات تحسين طفيفة. يُحقّق حدّ الاعتماد.\n• يحتاج إلى تحسين (50-69): مهارات محدّدة تتطلّب جلسات تدريب مركّزة.\n• منخفض (30-49): فجوات كبيرة في عدّة مجالات. يُوصى بتدريب إضافي.\n• حرج (أقلّ من 30): مهارات أساسية تحتاج إلى تطوير. يتطلّب إعادة تدريب بتوجيه مرشد.\n\nحدّ الاعتماد للتهيئة هو 70% (كفؤ).",
    category: 'report',
    docLink: '/knowledge-base/mcc-report-guide',
    options: [
      { label: "How do I improve my score?", labelAr: "كيف أُحسّن درجتي؟", nextNodeId: 'report-improve' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-dimensions': {
    id: 'report-dimensions',
    type: 'branch',
    text: "Which scoring dimension would you like to understand?",
    textAr: "أيّ بُعد من أبعاد التقييم تودّ فهمه؟",
    category: 'report',
    options: [
      { label: "Detection Accuracy (40%)", labelAr: "دقّة الكشف (40%)", nextNodeId: 'report-dim-detection' },
      { label: "False Positives (20%)", labelAr: "الإيجابيات الكاذبة (20%)", nextNodeId: 'report-dim-fp' },
      { label: "Timeliness (20%)", labelAr: "سرعة الاستجابة (20%)", nextNodeId: 'report-dim-time' },
      { label: "Attention & Gaze (20%)", labelAr: "الانتباه والنظر (20%)", nextNodeId: 'report-dim-gaze' },
    ],
  },
  'report-dim-detection': {
    id: 'report-dim-detection',
    type: 'answer',
    text: "Detection Accuracy (40% weight):\n\nMeasures how correctly you identified suspicious individuals during the scenario. This is the highest-weighted dimension because accurate threat detection is the core job of a CCTV operator.\n\nScored by: (Correct marks / Total threats) × 100\n\nTo improve: Study the scenario briefing carefully before the session. Know what suspicious behaviors to look for in each scenario type.",
    textAr: "دقّة الكشف (وزن 40%):\n\nيقيس مدى صحّة تحديدك للأشخاص المشتبه بهم خلال السيناريو. هذا هو البُعد الأعلى وزناً لأنّ الكشف الدقيق عن التهديدات هو المهمّة الأساسية لمشغّل كاميرات CCTV.\n\nطريقة الحساب: (التعليمات الصحيحة / إجمالي التهديدات) × 100\n\nللتحسين: ادرس ملخّص السيناريو بعناية قبل الجلسة. تعرّف على السلوكيات المشبوهة التي يجب البحث عنها في كلّ نوع من السيناريوهات.",
    category: 'report',
    options: [
      { label: "Explain another dimension", labelAr: "اشرح بُعداً آخر", nextNodeId: 'report-dimensions' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-dim-fp': {
    id: 'report-dim-fp',
    type: 'answer',
    text: "False Positives (20% weight):\n\nMeasures how many innocent individuals you incorrectly marked as suspicious. This is a penalty dimension, so more false positives = lower score.\n\nScored by: 100 - (False marks / Total marks × 100)\n\nTo improve: Be deliberate before marking. Look for multiple indicators of suspicious behavior rather than reacting to a single cue.",
    textAr: "الإيجابيات الكاذبة (وزن 20%):\n\nيقيس عدد الأشخاص الأبرياء الذين عُلِّموا خطأً كمشتبه بهم. هذا بُعد عقوبة، أي كلّما زادت الإيجابيات الكاذبة انخفضت الدرجة.\n\nطريقة الحساب: 100 - (التعليمات الخاطئة / إجمالي التعليمات × 100)\n\nللتحسين: كن متأنّياً قبل التعليم. ابحث عن عدّة مؤشّرات للسلوك المشبوه بدلاً من التفاعل مع إشارة واحدة.",
    category: 'report',
    options: [
      { label: "Explain another dimension", labelAr: "اشرح بُعداً آخر", nextNodeId: 'report-dimensions' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-dim-time': {
    id: 'report-dim-time',
    type: 'answer',
    text: "Timeliness (20% weight):\n\nMeasures how quickly you responded to events and alarms during the scenario. Faster responses indicate better situational awareness.\n\nScored by: Average response time compared to benchmark thresholds per scenario.\n\nTo improve: Keep alert for alarm indicators. Practice quick camera switching to investigate events promptly.",
    textAr: "سرعة الاستجابة (وزن 20%):\n\nيقيس مدى سرعة استجابتك للأحداث والإنذارات خلال السيناريو. تدلّ الاستجابات الأسرع على وعي ظرفي أفضل.\n\nطريقة الحساب: متوسّط وقت الاستجابة مقارنةً بالمعايير المرجعية لكلّ سيناريو.\n\nللتحسين: ابقَ متيقّظاً لمؤشّرات الإنذار. تدرّب على التبديل السريع بين الكاميرات للتحقيق في الأحداث فوراً.",
    category: 'report',
    options: [
      { label: "Explain another dimension", labelAr: "اشرح بُعداً آخر", nextNodeId: 'report-dimensions' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-dim-gaze': {
    id: 'report-dim-gaze',
    type: 'answer',
    text: "Attention & Gaze (20% weight):\n\nMeasures how well you distributed your visual attention across all camera feeds. Good operators don't fixate on one camera. They systematically scan all feeds.\n\nScored by: Eye tracking analysis of fixation distribution across all camera slots.\n\nTo improve: Practice the scan pattern and spend roughly equal time on each camera. Don't tunnel-vision on one feed.",
    textAr: "الانتباه والنظر (وزن 20%):\n\nيقيس مدى جودة توزيعك لانتباهك البصري على جميع بثوث الكاميرات. المشغّلون المتميّزون لا يُثبّتون نظرهم على كاميرا واحدة، بل يمسحون جميع البثوث بشكل منهجي.\n\nطريقة الحساب: تحليل تتبّع العين لتوزيع التثبيت على جميع خانات الكاميرات.\n\nللتحسين: تدرّب على نمط المسح واقضِ وقتاً متساوياً تقريباً على كلّ كاميرا. لا تُركّز بشكل مفرط على بثّ واحد.",
    category: 'report',
    options: [
      { label: "Explain another dimension", labelAr: "اشرح بُعداً آخر", nextNodeId: 'report-dimensions' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-improve': {
    id: 'report-improve',
    type: 'answer',
    text: "Tips to Improve Your Score:\n\n1. Study the scenario briefing.know what suspects look like and what to expect\n2. Practice the camera scan pattern.systematic, not random\n3. Be selective with marks.quality over quantity reduces false positives\n4. Respond to alarms immediately.every second counts for timeliness\n5. Use PTZ wisely.zoom in to confirm before marking\n6. Review your post-session report.identify which dimensions need work\n7. Use the Score Calculator tool to understand how each dimension affects your composite score",
    textAr: "نصائح لتحسين درجتك:\n\n1. ادرس ملخّص السيناريو. تعرّف على هيئة المشتبه بهم وما يمكن توقّعه\n2. تدرّب على نمط مسح الكاميرات. بشكل منهجي وليس عشوائياً\n3. كن انتقائياً في التعليمات. الجودة تُقلّل الإيجابيات الكاذبة\n4. استجب للإنذارات فوراً. كلّ ثانية مُحتسبة لسرعة الاستجابة\n5. استخدم PTZ بحكمة. قرّب الصورة للتأكّد قبل التعليم\n6. راجع تقريرك بعد الجلسة. حدّد الأبعاد التي تحتاج إلى تطوير\n7. استخدم أداة حاسبة الدرجات لفهم كيف يؤثّر كلّ بُعد على درجتك الإجمالية",
    category: 'report',
    docLink: '/tools/score-calculator',
    options: [
      { label: "Back to report help", labelAr: "العودة إلى مساعدة التقارير", nextNodeId: 'report-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'report-calculator': {
    id: 'report-calculator',
    type: 'answer',
    text: "The Score Calculator tool lets you input individual dimension scores and see how they combine into the composite score. You can experiment with different values to understand what it takes to reach your target score.\n\nTry it in the Tools section!",
    textAr: "تتيح لك أداة حاسبة الدرجات إدخال درجات الأبعاد الفردية ومعرفة كيفية اجتماعها في الدرجة الإجمالية. يمكنك تجربة قيم مختلفة لفهم ما تحتاجه للوصول إلى درجتك المستهدفة.\n\nجرّبها في قسم الأدوات!",
    category: 'report',
    docLink: '/tools/score-calculator',
    options: [
      { label: "Back to report help", labelAr: "العودة إلى مساعدة التقارير", nextNodeId: 'report-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },

  // ── ONBOARDING BRANCH ──
  'onboarding-start': {
    id: 'onboarding-start',
    type: 'branch',
    text: "Welcome aboard! Onboarding has 4 phases, and you move to the next one when you're ready. What's your role?",
    textAr: "مرحباً بك! تتكوّن التهيئة من 4 مراحل، وتنتقل إلى المرحلة التالية عندما تكون جاهزاً. ما هو دورك؟",
    category: 'onboarding',
    options: [
      { label: "I'm a new Operator", labelAr: "أنا مشغّل جديد", nextNodeId: 'onboard-operator' },
      { label: "I'm a new Supervisor", labelAr: "أنا مشرف جديد", nextNodeId: 'onboard-supervisor' },
      { label: "Show me the full onboarding process", labelAr: "أرِني عملية التهيئة الكاملة", nextNodeId: 'onboard-overview' },
    ],
  },
  'onboard-overview': {
    id: 'onboard-overview',
    type: 'answer',
    text: "MCCVR Onboarding Flow (4 Phases):\n\n📋 Phase 1: Orientation\n• Welcome briefing & facility tour\n• Mentor assignment\n• System access verification\n→ Move on when: mentor assigned and access confirmed\n\n🎓 Phase 2: Guided Practice\n• Hardware setup training\n• Run scenarios with mentor guidance\n• Receive feedback after each session\n→ Move on when: can set up own station, completed 3+ mentored scenarios\n\n🔄 Phase 3: Solo Practice\n• Independent execution\n• Mentor observes but doesn't guide\n• Complete competency checklist\n→ Move on when: all competency criteria met\n\n✅ Phase 4: Sign-Off\n• Achieve 70%+ composite score\n• Pass competency assessment\n• Receive certification\n→ Complete when: score achieved and checklist signed",
    textAr: "مسار تهيئة MCCVR (4 مراحل):\n\n📋 المرحلة 1: التوجيه\n• جلسة ترحيب وجولة في المنشأة\n• تعيين مرشد\n• التحقّق من صلاحيات الوصول إلى النظام\n← الانتقال عند: تعيين المرشد وتأكيد الصلاحيات\n\n🎓 المرحلة 2: التدريب الموجَّه\n• تدريب على إعداد الأجهزة\n• تشغيل سيناريوهات بتوجيه المرشد\n• تلقّي ملاحظات بعد كلّ جلسة\n← الانتقال عند: القدرة على إعداد المحطة ذاتياً، وإكمال 3 سيناريوهات موجَّهة أو أكثر\n\n🔄 المرحلة 3: التدريب المستقل\n• تنفيذ مستقل\n• المرشد يراقب دون توجيه\n• إكمال قائمة الكفاءات\n← الانتقال عند: تحقّق جميع معايير الكفاءة\n\n✅ المرحلة 4: الاعتماد\n• تحقيق 70%+ في الدرجة الإجمالية\n• اجتياز تقييم الكفاءة\n• الحصول على الشهادة\n← الاكتمال عند: تحقّق الدرجة وتوقيع قائمة التحقّق",
    category: 'onboarding',
    docLink: '/knowledge-base/mcc-onboarding-sop',
    options: [
      { label: "What score do I need to pass?", labelAr: "ما الدرجة المطلوبة للنجاح؟", nextNodeId: 'report-labels' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'onboard-operator': {
    id: 'onboard-operator',
    type: 'answer',
    text: "Welcome, new Operator! Here's your quick start path:\n\n1. Start with the Operator Quick Start Card (it's a one-page cheat sheet)\n2. Read the MCCVR Software Guide for the full system overview\n3. Your mentor will guide you through hardware setup during Guided Practice\n4. You'll work through all 5 scenarios at your own pace\n5. When you're ready, the sign-off requires a 70%+ composite score\n\nDon't worry about memorizing everything. The dashboard has all the reference materials you need!",
    textAr: "مرحباً بك أيّها المشغّل الجديد! إليك مسار البداية السريعة:\n\n1. ابدأ ببطاقة البداية السريعة للمشغّل (صفحة مرجعية واحدة)\n2. اقرأ دليل برنامج MCCVR للاطّلاع على النظرة الشاملة للنظام\n3. سيُرشدك المرشد في إعداد الأجهزة خلال مرحلة التدريب الموجَّه\n4. ستعمل على جميع السيناريوهات الخمسة وفق وتيرتك الخاصة\n5. عندما تكون جاهزاً، يتطلّب الاعتماد تحقيق 70%+ في الدرجة الإجمالية\n\nلا تقلق بشأن حفظ كلّ شيء. تحتوي لوحة التحكّم على جميع المواد المرجعية التي تحتاجها!",
    category: 'onboarding',
    docLink: '/knowledge-base/mcc-operator-quick-start',
    options: [
      { label: "How does the VR headset work?", labelAr: "كيف تعمل نظارة VR؟", nextNodeId: 'hardware-headset' },
      { label: "What are the 5 scenarios?", labelAr: "ما هي السيناريوهات الخمسة؟", nextNodeId: 'scenarios-overview' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'onboard-supervisor': {
    id: 'onboard-supervisor',
    type: 'answer',
    text: "Welcome, new Supervisor! Here's your quick start path:\n\n1. Start with the Supervisor Quick Start Card\n2. Read the MCCVR Software Guide and Report Guide\n3. Your onboarding covers both operating the system and managing sessions\n4. You'll learn to host sessions, monitor operators, and generate reports\n5. The sign-off assessment covers both system operation and team management\n\nSupervisors need to understand both the operator experience and the monitoring dashboard.",
    textAr: "مرحباً بك أيّها المشرف الجديد! إليك مسار البداية السريعة:\n\n1. ابدأ ببطاقة البداية السريعة للمشرف\n2. اقرأ دليل برنامج MCCVR ودليل التقارير\n3. تُغطّي تهيئتك تشغيل النظام وإدارة الجلسات\n4. ستتعلّم استضافة الجلسات، ومراقبة المشغّلين، وإنشاء التقارير\n5. يُغطّي تقييم الاعتماد تشغيل النظام وإدارة الفريق\n\nيحتاج المشرفون إلى فهم تجربة المشغّل ولوحة المراقبة على حدٍّ سواء.",
    category: 'onboarding',
    docLink: '/knowledge-base/mcc-supervisor-quick-start',
    options: [
      { label: "How do I host a session?", labelAr: "كيف أستضيف جلسة؟", nextNodeId: 'session-supervisor' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },

  // ── SCORING BRANCH ──
  'scoring-start': {
    id: 'scoring-start',
    type: 'branch',
    text: "What do you want to know about how scoring works?",
    textAr: "ماذا تودّ أن تعرف عن آلية حساب الدرجات؟",
    category: 'scoring',
    options: [
      { label: "How is my score calculated?", labelAr: "كيف تُحسب درجتي؟", nextNodeId: 'report-composite' },
      { label: "What score do I need to pass?", labelAr: "ما الدرجة المطلوبة للنجاح؟", nextNodeId: 'report-labels' },
      { label: "Explain each scoring dimension", labelAr: "اشرح كلّ بُعد من أبعاد التقييم", nextNodeId: 'report-dimensions' },
      { label: "Tips to improve my score", labelAr: "نصائح لتحسين درجتي", nextNodeId: 'report-improve' },
      { label: "Try the Score Calculator", labelAr: "جرّب حاسبة الدرجات", nextNodeId: 'report-calculator' },
    ],
  },

  // ── HARDWARE BRANCH ──
  'hardware-start': {
    id: 'hardware-start',
    type: 'branch',
    text: "What hardware do you need help with?",
    textAr: "بأيّ جهاز تحتاج إلى مساعدة؟",
    category: 'hardware',
    options: [
      { label: "VR Headset (HTC Vive Focus Vision)", labelAr: "نظارة VR (HTC Vive Focus Vision)", nextNodeId: 'hardware-headset' },
      { label: "EmotiBit biometric sensor", labelAr: "مستشعر EmotiBit الحيوي", nextNodeId: 'hardware-emotibit' },
      { label: "Workstation PC specs", labelAr: "مواصفات حاسوب محطة العمل", nextNodeId: 'hardware-pc' },
      { label: "Network setup", labelAr: "إعداد الشبكة", nextNodeId: 'hardware-network' },
    ],
  },
  'hardware-headset': {
    id: 'hardware-headset',
    type: 'answer',
    text: "HTC Vive Focus Vision Headset:\n\n• VR headset used by all operators\n• Supports eye tracking (used for gaze analysis scoring)\n• Must be charged before each session\n• Connected to the PC using a Link Cable (USB) through VIVE Hub / SteamVR\n• Standard warranty: 1 year (expires Feb 2027)\n\nPutting on the headset:\n1. Adjust the head strap for a snug fit\n2. Use the IPD (inter-pupillary distance) dial for focus\n3. Complete the eye tracking calibration when prompted",
    textAr: "نظارة HTC Vive Focus Vision:\n\n• نظارة VR يستخدمها جميع المشغّلين\n• تدعم تتبّع العين (تُستخدم لتقييم تحليل النظر)\n• يجب شحنها قبل كلّ جلسة\n• تتصل بالحاسوب باستخدام Link Cable عبر USB من خلال VIVE Hub / SteamVR\n• الضمان القياسي: سنة واحدة (ينتهي في فبراير 2027)\n\nارتداء النظارة:\n1. اضبط شريط الرأس ليكون مُحكماً\n2. استخدم قرص IPD (المسافة بين الحدقتين) لضبط التركيز\n3. أكمل معايرة تتبّع العين عند ظهور المطالبة",
    category: 'hardware',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "Headset won't connect", labelAr: "النظارة لا تتصل", nextNodeId: 'ts-vr-connect' },
      { label: "Back to hardware", labelAr: "العودة إلى الأجهزة", nextNodeId: 'hardware-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'hardware-emotibit': {
    id: 'hardware-emotibit',
    type: 'answer',
    text: "EmotiBit Biometric Sensor:\n\n• Wrist-worn sensor measuring physiological signals\n• Captures: Heart rate (HR), Skin conductance (EDA), Temperature\n• Used for stress analysis during training scenarios\n• Connects to the PC via the router's wireless network on UDP port 12346\n• LED indicators: Green = streaming, Blue = searching, Red = error\n\nSetup (before launching MCCVR):\n1. Charge the sensor and turn it on\n2. Remove any jewelry from that wrist (rings, bracelets, watches). Metal can cause tingling\n3. Wear the sensor on your wrist with a snug fit\n3. Open the EmotiBit Oscilloscope app on the PC\n4. Select the correct EmotiBit device in output devices\n5. Set transfer mode to UDP\n6. Verify the LED turns green (connected and streaming)",
    textAr: "مستشعر EmotiBit الحيوي:\n\n• مستشعر يُرتدى على المعصم لقياس الإشارات الفسيولوجية\n• يلتقط: معدّل نبض القلب (HR)، التوصيل الجلدي (EDA)، الحرارة\n• يُستخدم لتحليل التوتّر خلال سيناريوهات التدريب\n• يتصل بالحاسوب عبر الشبكة اللاسلكية للموجّه على منفذ UDP 12346\n• مؤشّرات LED: أخضر = يبثّ، أزرق = يبحث، أحمر = خطأ\n\nالإعداد (قبل تشغيل MCCVR):\n1. اشحن المستشعر وشغّله\n2. أزِل أيّ مجوهرات من ذلك المعصم (خواتم، أساور، ساعات). قد تُسبّب المعادن وخزاً\n3. ارتدِ المستشعر على معصمك بإحكام\n3. افتح تطبيق EmotiBit Oscilloscope على الحاسوب\n4. اختر جهاز EmotiBit الصحيح في أجهزة الإخراج\n5. اضبط وضع النقل على UDP\n6. تأكّد من تحوّل مؤشّر LED إلى اللون الأخضر (متصل ويبثّ)",
    category: 'hardware',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "EmotiBit has issues", labelAr: "توجد مشكلات في EmotiBit", nextNodeId: 'ts-emotibit' },
      { label: "Back to hardware", labelAr: "العودة إلى الأجهزة", nextNodeId: 'hardware-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'hardware-pc': {
    id: 'hardware-pc',
    type: 'answer',
    text: "MCCVR Workstation Requirements:\n\n• 9 PCs total: 8 operator stations + 1 supervisor station\n• Minimum GPU: NVIDIA RTX 2060\n• Recommended GPU: RTX 3070 or higher\n• OS: Windows 10/11 Pro\n• Network: Gigabit Ethernet (wired only)\n• Hardware warranty: 3 years on-site (expires Feb 2029)\n\nAll PCs must be connected to the same network switch for low-latency communication.",
    textAr: "متطلّبات محطة عمل MCCVR:\n\n• 9 أجهزة حاسوب إجمالاً: 8 محطات مشغّلين + 1 محطة مشرف\n• الحدّ الأدنى لـ GPU: NVIDIA RTX 2060\n• GPU المُوصى به: RTX 3070 أو أعلى\n• نظام التشغيل: Windows 10/11 Pro\n• الشبكة: Gigabit Ethernet (سلكي فقط)\n• ضمان الأجهزة: 3 سنوات في الموقع (ينتهي في فبراير 2029)\n\nيجب أن تكون جميع أجهزة الحاسوب متصلة بمحوّل الشبكة ذاته لضمان اتصال منخفض التأخير.",
    category: 'hardware',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "Network setup", labelAr: "إعداد الشبكة", nextNodeId: 'hardware-network' },
      { label: "Back to hardware", labelAr: "العودة إلى الأجهزة", nextNodeId: 'hardware-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'hardware-network': {
    id: 'hardware-network',
    type: 'answer',
    text: "MCCVR Network Configuration:\n\n• All 9 PCs connected via Gigabit Ethernet switch\n• Key ports:\n  - TCP 7777: Session communication\n  - UDP 7780+: Additional session traffic\n  - UDP 12346: EmotiBit biometric data\n• Supervisor PC acts as the server (bSupervisor=True)\n• Server config: Content/Configs/Server.json\n• Windows Firewall must allow MCC through on all required ports\n\nNo internet connection required. Everything runs on the local network.",
    textAr: "إعداد شبكة MCCVR:\n\n• جميع الأجهزة التسعة متصلة عبر محوّل Gigabit Ethernet\n• المنافذ الرئيسية:\n  - TCP 7777: اتصال الجلسة\n  - UDP 7780+: حركة بيانات الجلسة الإضافية\n  - UDP 12346: بيانات EmotiBit الحيوية\n• حاسوب المشرف يعمل كـ Server (bSupervisor=True)\n• إعدادات Server: Content/Configs/Server.json\n• يجب أن يسمح Windows Firewall لـ MCCVR بالمرور على جميع المنافذ المطلوبة\n\nلا يُشترط اتصال بالإنترنت. يعمل كلّ شيء على الشبكة المحلية.",
    category: 'hardware',
    docLink: '/knowledge-base/mcc-operator-setup-guide',
    options: [
      { label: "View network diagram", labelAr: "عرض مخطّط الشبكة", nextNodeId: 'hardware-network-diagram' },
      { label: "Back to hardware", labelAr: "العودة إلى الأجهزة", nextNodeId: 'hardware-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
  'hardware-network-diagram': {
    id: 'hardware-network-diagram',
    type: 'answer',
    text: "The System Architecture page has an interactive network diagram showing all 9 PCs, the network switch, and port assignments. You can click on any node to see its specifications and relevant documentation.",
    textAr: "تحتوي صفحة هندسة النظام على مخطّط شبكة تفاعلي يعرض جميع الأجهزة التسعة ومحوّل الشبكة وتعيينات المنافذ. يمكنك النقر على أيّ عقدة لعرض مواصفاتها والوثائق ذات الصلة.",
    category: 'hardware',
    docLink: '/tools/architecture',
    options: [
      { label: "Back to hardware", labelAr: "العودة إلى الأجهزة", nextNodeId: 'hardware-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },

  // ── SCENARIOS OVERVIEW (linked from onboarding) ──
  'scenarios-overview': {
    id: 'scenarios-overview',
    type: 'answer',
    text: "MCCVR Training Scenarios (5 Abu Dhabi locations):\n\n1. 🛫 Airport.Main entrance monitoring, suspicious item detection\n2. 🏛️ Embassy.Restricted access areas, counter-surveillance\n3. 🏬 Shopping Mall.Crowded public space monitoring\n4. 🎵 Concert (Etihad Park).Large crowd event management\n5. ✊ Protest (Musaffah).High-tension crowd scenario\n\nEach scenario has unique threats, camera positions, and scoring criteria. Difficulty increases from Airport (beginner-friendly) to Protest (advanced).",
    textAr: "سيناريوهات تدريب MCCVR (5 مواقع في أبوظبي):\n\n1. 🛫 المطار. مراقبة المدخل الرئيسي، كشف العناصر المشبوهة\n2. 🏛️ السفارة. مناطق وصول مقيّد، مكافحة المراقبة\n3. 🏬 المركز التجاري. مراقبة أماكن عامة مزدحمة\n4. 🎵 الحفلة (Etihad Park). إدارة فعاليات الحشود الكبيرة\n5. ✊ الاحتجاج (مصفّح). سيناريو حشود عالي التوتّر\n\nيتضمّن كلّ سيناريو تهديدات فريدة ومواضع كاميرات ومعايير تقييم خاصة. تزداد الصعوبة من المطار (مناسب للمبتدئين) إلى الاحتجاج (متقدّم).",
    category: 'scenarios',
    docLink: '/scenarios',
    options: [
      { label: "Back to onboarding", labelAr: "العودة إلى التهيئة", nextNodeId: 'onboarding-start' },
      { label: "Back to main menu", labelAr: "العودة إلى القائمة الرئيسية", nextNodeId: 'root' },
    ],
  },
};
