import type { DocMeta, DocCategory, Role } from '../types/content';

// All document metadata (acts as our database)
export const documents: DocMeta[] = [
  {
    id: 'mcc-software-guide',
    title: 'MCCVR Software Guide',
    titleAr: 'دليل برنامج MCCVR',
    category: 'guides',
    roles: ['operator', 'supervisor'],
    tags: ['software', 'vr', 'session', 'scoring', 'overview'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Complete user guide for the MCCVR CCTV Training System covering system overview, software usage, scoring methodology, and troubleshooting.',
    summaryAr: 'دليل المستخدم الشامل لنظام التدريب MCCVR CCTV يغطي نظرة عامة على النظام واستخدام البرنامج ومنهجية التقييم واستكشاف الأخطاء وإصلاحها.',
    related: ['mcc-report-guide', 'mcc-operator-quick-start', 'mcc-supervisor-quick-start'],
    filePath: 'guides/MCC_Software_Guide.md',
  },
  {
    id: 'mcc-onboarding-sop',
    title: 'MCCVR Onboarding SOP',
    titleAr: 'إجراءات التهيئة MCCVR',
    category: 'sops',
    roles: ['operator', 'supervisor', 'facilitator', 'it-admin'],
    tags: ['onboarding', 'sop', 'training', 'phases', 'mentorship'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Flow-based onboarding procedure: Orientation, Guided Practice, Solo Practice, and Sign-Off. Progress at your own pace.',
    summaryAr: 'إجراء تهيئة قائم على المراحل: التوجيه، التدريب الموجّه، التدريب الفردي، والاعتماد النهائي. تقدّم بالسرعة التي تناسبك.',
    related: ['mcc-mentor-assignment-form', 'mcc-competency-checklist-operator', 'mcc-competency-checklist-supervisor'],
    filePath: 'sops/MCC_Onboarding_SOP.md',
  },
  {
    id: 'mcc-operator-setup-guide',
    title: 'MCCVR Operator Setup Guide v1.2',
    titleAr: 'دليل إعداد محطة المشغّل MCCVR الإصدار 1.2',
    category: 'guides',
    roles: ['operator', 'it-admin'],
    tags: ['setup', 'hardware', 'workstation', 'network', 'emotibit', 'operator'],
    version: '1.2',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Detailed hardware and software setup for operator workstations including PC configuration, VR headset setup, EmotiBit sensor configuration, and network settings.',
    summaryAr: 'إعداد تفصيلي للأجهزة والبرامج لمحطات المشغّل يشمل تهيئة الحاسوب وإعداد نظارة VR وتكوين مستشعر EmotiBit وإعدادات الشبكة.',
    related: ['mcc-station-setup-guide', 'mcc-operator-quick-start', 'mcc-troubleshooting-flowchart'],
    filePath: 'guides/MCC_Operator_Setup_GuideV1.2.md',
  },
  {
    id: 'mcc-supervisor-setup-guide',
    title: 'MCCVR Supervisor Setup Guide v1.2',
    titleAr: 'دليل إعداد محطة المشرف MCCVR الإصدار 1.2',
    category: 'guides',
    roles: ['supervisor', 'it-admin'],
    tags: ['setup', 'hardware', 'workstation', 'supervisor', 'dashboard'],
    version: '1.2',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Detailed hardware and software setup for the supervisor station including dashboard configuration and monitoring tools.',
    summaryAr: 'إعداد تفصيلي للأجهزة والبرامج لمحطة المشرف يشمل تهيئة لوحة المعلومات وأدوات المراقبة.',
    related: ['mcc-station-setup-guide', 'mcc-supervisor-quick-start', 'mcc-troubleshooting-flowchart'],
    filePath: 'guides/MCC_Supervisor_Setup_GuideV1.2.md',
  },
  {
    id: 'mcc-facilitator-guide-new',
    title: 'MCCVR Facilitator Guide',
    titleAr: 'دليل الميسّر MCCVR',
    category: 'training',
    roles: ['facilitator'],
    tags: ['facilitator', 'instructor', 'training', 'session', 'delivery'],
    version: '2.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Instructor script and session delivery guide for the 3.5-hour training block (30% talking, 70% hands-on). Includes the full 4-block session structure.',
    summaryAr: 'نص المدرّب ودليل تقديم الجلسة للكتلة التدريبية التي تستغرق 3.5 ساعات (30% شرح، 70% تطبيق عملي). يتضمن هيكل الجلسة الكامل المكوّن من 4 كتل.',
    related: ['mcc-onboarding-sop', 'mcc-training-knowledge-transfer'],
    filePath: 'training/MCC_Facilitator_Guide_NEW.md',
  },
  {
    id: 'mcc-report-guide',
    title: 'MCCVR Report Guide',
    titleAr: 'دليل تقارير MCCVR',
    category: 'guides',
    roles: ['operator', 'supervisor', 'facilitator'],
    tags: ['report', 'scoring', 'metrics', 'performance', 'assessment'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: "Reader's guide for interpreting operator performance reports: composite scoring, detection accuracy, false positives, timeliness, and attention metrics.",
    summaryAr: 'دليل القارئ لتفسير تقارير أداء المشغّل: التقييم المركّب ودقة الكشف والإنذارات الكاذبة والالتزام بالوقت ومقاييس الانتباه.',
    related: ['mcc-software-guide', 'mcc-assessment-checklist-operator'],
    filePath: 'guides/MCC_Report_Guide.md',
  },
  {
    id: 'mcc-station-setup-guide',
    title: 'MCCVR Station Setup Guide',
    titleAr: 'دليل إعداد محطة MCCVR',
    category: 'guides',
    roles: ['it-admin', 'facilitator'],
    tags: ['station', 'setup', 'physical', 'workstation', 'layout'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Physical workstation layout and preparation guide for the MCCVR training facility.',
    summaryAr: 'دليل تخطيط وتجهيز محطات العمل الفعلية لمرفق التدريب MCCVR.',
    related: ['mcc-operator-setup-guide', 'mcc-supervisor-setup-guide'],
    filePath: 'guides/MCC_Station_Setup_Guide.md',
  },
  {
    id: 'mcc-training-knowledge-transfer',
    title: 'MCCVR Training Knowledge Transfer Plan v2.0',
    titleAr: 'خطة نقل المعرفة التدريبية MCCVR الإصدار 2.0',
    category: 'training',
    roles: ['facilitator', 'it-admin'],
    tags: ['training', 'knowledge-transfer', 'documentation', 'strategy'],
    version: '2.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Training and documentation strategy for MCCVR User Manual, Training Sessions, and Onboarding procedures.',
    summaryAr: 'استراتيجية التدريب والتوثيق لدليل مستخدم MCCVR وجلسات التدريب وإجراءات التهيئة.',
    related: ['mcc-onboarding-sop', 'mcc-facilitator-guide-new'],
    filePath: 'training/MCC_Training_Knowledge_Transfer_Plan_v2.0.md',
  },
  {
    id: 'mcc-isnr-2026-setup',
    title: 'ISNR 2026 MCCVR Training Booth Setup',
    titleAr: 'إعداد جناح تدريب MCCVR في ISNR 2026',
    category: 'reference',
    roles: ['it-admin', 'facilitator'],
    tags: ['isnr', 'event', 'booth', 'setup', 'exhibition'],
    version: '2.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Technical requirements for the MCCVR booth at ISNR 2026 event (May 19-21): two setup options (minimal and expanded).',
    summaryAr: 'المتطلبات التقنية لجناح MCCVR في فعالية ISNR 2026 (19-21 مايو): خياران للإعداد (الحد الأدنى والموسّع).',
    related: ['mcc-station-setup-guide'],
    filePath: 'reference/ISNR_2026_MCC_VR_Training_Booth_Technical_Setup_Requirements_V2.md',
  },
  {
    id: 'mcc-assessment-checklist-operator',
    title: 'MCCVR Assessment Checklist:Operator',
    titleAr: 'قائمة تقييم MCCVR: المشغّل',
    category: 'forms',
    roles: ['operator', 'facilitator'],
    tags: ['assessment', 'checklist', 'operator', 'evaluation', 'sign-off'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Formal assessment form for operator evaluation during onboarding sign-off phase.',
    summaryAr: 'نموذج التقييم الرسمي لتقييم المشغّل خلال مرحلة الاعتماد النهائي في التهيئة.',
    related: ['mcc-onboarding-sop', 'mcc-competency-checklist-operator'],
    filePath: 'forms/MCC_Assessment_Checklist_Operator.md',
  },
  {
    id: 'mcc-assessment-checklist-supervisor',
    title: 'MCCVR Assessment Checklist:Supervisor',
    titleAr: 'قائمة تقييم MCCVR: المشرف',
    category: 'forms',
    roles: ['supervisor', 'facilitator'],
    tags: ['assessment', 'checklist', 'supervisor', 'evaluation', 'sign-off'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Formal assessment form for supervisor evaluation during onboarding sign-off phase.',
    summaryAr: 'نموذج التقييم الرسمي لتقييم المشرف خلال مرحلة الاعتماد النهائي في التهيئة.',
    related: ['mcc-onboarding-sop', 'mcc-competency-checklist-supervisor'],
    filePath: 'forms/MCC_Assessment_Checklist_Supervisor.md',
  },
  {
    id: 'mcc-competency-checklist-operator',
    title: 'MCCVR Competency Checklist:Operator',
    titleAr: 'قائمة الكفاءات MCCVR: المشغّل',
    category: 'forms',
    roles: ['operator', 'facilitator'],
    tags: ['competency', 'checklist', 'operator', 'mentor', 'observation'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Mentor observation form with 13 competency criteria for operators during the Solo Practice phase.',
    summaryAr: 'نموذج ملاحظة المرشد يتضمن 13 معيار كفاءة للمشغّلين خلال مرحلة التدريب الفردي.',
    related: ['mcc-onboarding-sop', 'mcc-assessment-checklist-operator'],
    filePath: 'forms/MCC_Competency_Checklist_Operator.md',
  },
  {
    id: 'mcc-competency-checklist-supervisor',
    title: 'MCCVR Competency Checklist:Supervisor',
    titleAr: 'قائمة الكفاءات MCCVR: المشرف',
    category: 'forms',
    roles: ['supervisor', 'facilitator'],
    tags: ['competency', 'checklist', 'supervisor', 'mentor', 'observation'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Mentor observation form for supervisors during onboarding.',
    summaryAr: 'نموذج ملاحظة المرشد للمشرفين خلال فترة التهيئة.',
    related: ['mcc-onboarding-sop', 'mcc-assessment-checklist-supervisor'],
    filePath: 'forms/MCC_Competency_Checklist_Supervisor.md',
  },
  {
    id: 'mcc-mentor-assignment-form',
    title: 'MCCVR Mentor Assignment Form',
    titleAr: 'نموذج تعيين المرشد MCCVR',
    category: 'forms',
    roles: ['facilitator', 'it-admin'],
    tags: ['mentor', 'assignment', 'form', 'onboarding'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Form to formally assign mentors and new hires for the MCCVR onboarding process.',
    summaryAr: 'نموذج لتعيين المرشدين والموظفين الجدد رسميًا لعملية التهيئة في MCCVR.',
    related: ['mcc-onboarding-sop'],
    filePath: 'forms/MCC_Mentor_Assignment_Form.md',
  },
  {
    id: 'mcc-operator-quick-start',
    title: 'MCCVR Operator Quick Start Card',
    titleAr: 'بطاقة البدء السريع للمشغّل MCCVR',
    category: 'reference',
    roles: ['operator'],
    tags: ['quick-start', 'reference', 'card', 'operator'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Single-page quick reference card for operators: boot sequence, VR setup, session join, and key controls.',
    summaryAr: 'بطاقة مرجعية سريعة من صفحة واحدة للمشغّلين: تسلسل التشغيل وإعداد VR والانضمام للجلسة وأهم عناصر التحكم.',
    related: ['mcc-software-guide', 'mcc-operator-setup-guide'],
    filePath: 'reference/MCC_Operator_Quick_Start_Card.md',
  },
  {
    id: 'mcc-supervisor-quick-start',
    title: 'MCCVR Supervisor Quick Start Card',
    titleAr: 'بطاقة البدء السريع للمشرف MCCVR',
    category: 'reference',
    roles: ['supervisor'],
    tags: ['quick-start', 'reference', 'card', 'supervisor'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Single-page quick reference card for supervisors: session creation, monitoring, report generation.',
    summaryAr: 'بطاقة مرجعية سريعة من صفحة واحدة للمشرفين: إنشاء الجلسة والمراقبة وإعداد التقارير.',
    related: ['mcc-software-guide', 'mcc-supervisor-setup-guide'],
    filePath: 'reference/MCC_Supervisor_Quick_Start_Card.md',
  },
  {
    id: 'mcc-troubleshooting-flowchart',
    title: 'MCCVR Troubleshooting Flowchart',
    titleAr: 'مخطط استكشاف الأخطاء وإصلاحها MCCVR',
    category: 'reference',
    roles: ['operator', 'supervisor', 'it-admin'],
    tags: ['troubleshooting', 'flowchart', 'issues', 'problems', 'fixes'],
    version: '1.0',
    date: '2026-04',
    lastUpdated: '2026-04-07',
    classification: 'Confidential',
    summary: 'Decision tree for diagnosing and resolving common MCCVR technical issues.',
    summaryAr: 'شجرة قرارات لتشخيص وحل المشكلات التقنية الشائعة في MCCVR.',
    related: ['mcc-operator-setup-guide', 'mcc-supervisor-setup-guide'],
    filePath: 'reference/MCC_Troubleshooting_Flowchart.md',
  },
];

export const categoryLabels: Record<DocCategory, string> = {
  guides: 'Guides',
  sops: 'Standard Operating Procedures',
  scenarios: 'Scenarios',
  training: 'Training',
  forms: 'Forms & Checklists',
  reference: 'Reference',
  meta: 'Meta',
};

export const categoryLabelsAr: Record<DocCategory, string> = {
  guides: 'الأدلة',
  sops: 'إجراءات التشغيل القياسية',
  scenarios: 'السيناريوهات',
  training: 'التدريب',
  forms: 'النماذج وقوائم المراجعة',
  reference: 'المراجع',
  meta: 'معلومات عامة',
};

export const roleLabels: Record<Role | 'all', string> = {
  all: 'All Roles',
  operator: 'Operator',
  supervisor: 'Supervisor',
  facilitator: 'Facilitator',
  'it-admin': 'IT / Admin',
};

export const roleLabelsAr: Record<Role | 'all', string> = {
  all: 'جميع الأدوار',
  operator: 'المشغّل',
  supervisor: 'المشرف',
  facilitator: 'الميسّر',
  'it-admin': 'تقنية المعلومات / الإدارة',
};

export const roleColors: Record<Role, string> = {
  operator: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  supervisor: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  facilitator: 'bg-green-500/20 text-green-400 border-green-500/30',
  'it-admin': 'bg-orange-500/20 text-orange-400 border-orange-500/30',
};

export function getDocById(id: string): DocMeta | undefined {
  return documents.find(d => d.id === id);
}

export function getDocsByCategory(category: DocCategory): DocMeta[] {
  return documents.filter(d => d.category === category);
}

export function getDocsByRole(role: Role | 'all'): DocMeta[] {
  if (role === 'all') return documents;
  return documents.filter(d => d.roles.includes(role));
}

export function getRelatedDocs(doc: DocMeta): DocMeta[] {
  return doc.related
    .map(id => getDocById(id))
    .filter((d): d is DocMeta => d !== undefined);
}
